name: Pytest Pypi

on:
  push:
    branches:
      - master
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: docker run
        run: >-
          docker
          run
          -v $GITHUB_WORKSPACE/pytest_gcs/storage/data:/data
          -d 
          -p 9023:9023
          --name storage_emulator
          fsouza/fake-gcs-server
          -port 9023
          -scheme http
          -backend memory
          -public-host 127.0.0.1:9023
          -external-url http://127.0.0.1:9023
          -filesystem-root
          /storage

      - name: pytest
        run: |
          python -m pip install . -r tests/requirements-dev.txt
          INTEGRATION_DEPLOYMENT_ENV=1 pytest -vv

  pypi:
    runs-on: ubuntu-latest
    needs: [pytest]
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build
        run: |
          python -m pip install build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1